### ISSUE TITLE
HACS incompatible ?

### ISSUE THREAD

**Issue by macrumpel** [Layf21/hass-froeling-connect#1]
When I click on download in HACS, it says

The version a3e0057 for this integration can not be used with HACS

HA latest version running on Docker on a pi4b.

**Comment by macrumpel** [comment]
The commit by lugg1 https://github.com/Layf21/hass-froeling-connect/pull/3 did it for me

**Comment by piet2011** [comment]
Ich habe auch das Problem Die Version a3e0057 für diese Integration kann nicht mit HACS verwendet werden

**Comment by PetaPi314** [comment]
I have the same problem. Did a manual install to fix it. But this can be easily fixed.
Thx @lugg1 for the fix.

**Comment by piet2011** [comment]
> Ich habe das gleiche Problem. Habe eine manuelle Installation durchgeführt, um das Problem zu beheben. Aber das lässt sich leicht beheben. Danke für die Lösung.

Hallo und wie hast du das manuell installiert?

**Comment by Layf21** [comment]
I did not expect this integration to have so many users already. I will update and maintain this integration more actively now. The PR has been merged, it should be fixed.

**Comment by piet2011** [comment]
> Ich hatte nicht erwartet, dass diese Integration bereits so viele Benutzer hat. Ich werde diese Integration jetzt aktiver aktualisieren und pflegen. Die PR wurde zusammengeführt, sie sollte behoben sein.

Super vielen Dank 5 Sterne weiter so läuft jetzt Super Danke für deine Mühe
